### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by Wangkaixinlove** [berlino/SA-Sent#4]
您好，最近读了您的论文，有一些不明白的地方，比如说若一句话中含有两个目标，我怎么对它进行标注呢？标注目标、标注表达意见的词以及表达意见的词的情感类别？这样会不会太麻烦了呢？还有就是最后的结果是判断每个目标分别的情感对吗？这个结果如何得出呢？因为之前都是一句话的情感，最后生成一个每类情感的概率，您这个是生成每个目标分别每类情感概率吗？您举得模型是一个目标及它的意见表达，所以有点不明白。可以交流下吗？请问您邮箱是什么呢？

**Comment by berlino** [comment]
如果一个句子有两个target的话，那么模型就需要跑两次： 每次都会针对某个target生成sentiment和latent opinion. 具体可以看最后运行输出的latent opinion也可理解。
问题可以发我邮箱 bailin.wang@ed.ac.uk

**Comment by Wangkaixinlove** [comment]
谢谢您的回答，我还有两个问题，一个是您的训练硬件是什么呢？CPU大约多少G？还有一个我看数据并没有标注每个目标的潜在意见，比如您举的例子：service&nbsp;is quite&nbsp;terrible.我的理解是将目标service、目标的情感negtive、表达目标的潜在意见、这三种表示出来，然后经过反向传播训练Wtag、Wv、We这三个矩阵以及前面一系列LSTM相关的矩阵和参数，但是我发现并没有将表达目标的潜在意见标注出来呀？那Wv、We如何训练呢？是我理解错了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bailin"<notifications@github.com&gt;; 
发送时间: 2019年11月2日(星期六) 中午11:18
收件人: "berlino/SA-Sent"<SA-Sent@noreply.github.com&gt;; 
抄送: "491045545"<491045545@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [berlino/SA-Sent] QUESTION (#4)




如果一个句子有两个target的话，那么模型就需要跑两次： 每次都会针对某个target生成sentiment和latent opinion. 具体可以看最后运行输出的latent opinion也可理解。
 问题可以发我邮箱 bailin.wang@ed.ac.uk

**Comment by Wangkaixinlove** [comment]
我在网上下载TASK4的数据集没有手工标注的潜在意见，您方便发一份数据给我吗，我想跑一遍代码，看看每层输出，更深的理解下论文，如果可以的话，万分感谢！！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bailin"<notifications@github.com&gt;; 
发送时间: 2019年11月2日(星期六) 中午11:18
收件人: "berlino/SA-Sent"<SA-Sent@noreply.github.com&gt;; 
抄送: "491045545"<491045545@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [berlino/SA-Sent] QUESTION (#4)




如果一个句子有两个target的话，那么模型就需要跑两次： 每次都会针对某个target生成sentiment和latent opinion. 具体可以看最后运行输出的latent opinion也可理解。
 问题可以发我邮箱 bailin.wang@ed.ac.uk
